### ISSUE TITLE
A white displaying issue

### ISSUE THREAD

**Issue by Abslb** [nihaocun/Kirby-Assistant#1]
有时后某些安卓系统点进某一个分项之后再退出来界面会变白

**Comment by Yanren1225** [comment]
这是因为rxjava导致的
(另外你标题用英文我还懵了一会儿:rolling_on_the_floor_laughing:)

**Comment by Abslb** [comment]
然而这个问题还是没解决哈，smartisan os4.0.0.1,安卓版本7.1.1，处理器sdm660，内存(运行内存)4G

**Comment by Yanren1225** [comment]
很抱歉现在回复
问题已经在修复1.3.2了
